name: Model Retraining & Docker Build

on:
  push:
    branches: [ main ]
    # Diperlebar agar perubahan di folder MLProject apa pun memicu retraining
    paths: 
      - 'Workflow-CI/MLProject/**'
  # Menambahkan ini agar tombol "Run workflow" muncul di tab Actions
  workflow_dispatch: 

jobs:
  retrain-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn docker

      - name: Run Training (MLflow Project)
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Masuk ke folder MLProject yang ada di dalam Workflow-CI
          cd Workflow-CI/MLProject
          mlflow run . -P n_estimators=120

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with MLflow
        run: |
          # Masuk ke folder yang sama untuk build docker
          cd Workflow-CI/MLProject
          mlflow models build-docker -m "model_retrained" -n "${{ secrets.DOCKERHUB_USERNAME }}/car-price-predictor:latest"
          
      - name: Push Image to Docker Hub
        run: docker push ad3whyu/car-price-predictor:latest