name: Model Retraining & Docker Build

on:
  push:
    branches: [ main ]
    paths: 
      - 'MLProject/**'
  workflow_dispatch: 

jobs:
  retrain-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn docker

      - name: Run Training
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/ad3whyu/Eksperimen_SML_Ade-Wahyu-Warpudin.mlflow
          MLFLOW_TRACKING_USERNAME: ad3whyu
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Menjalankan project MLflow dengan --env-manager=local
          mlflow run MLProject/ --env-manager=local -P n_estimators=120 -P max_depth=10 -P min_samples_split=2

      - name: Verify Model Folder
        working-directory: MLProject
        run: |
          # Memastikan folder model_retrained benar-benar ada sebelum build docker
          ls -la
          ls -R model_retrained

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with MLflow
        working-directory: MLProject
        run: |
          # Membangun image dari folder model_retrained yang dibuat oleh modelling.py
          mlflow models build-docker -m "model_retrained" -n "${{ secrets.DOCKERHUB_USERNAME }}/car-price-predictor:latest" --install-mlflow
          
      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/car-price-predictor:latest