name: Model Retraining & Docker Build

on:
  push:
    branches: [ main ]
    paths: [ 'Workflow-CI/MLProject/modelling.py' ]

jobs:
  retrain-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn docker

      - name: Run Training (MLflow Project)
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd Workflow-CI/MLProject
          mlflow run . -P n_estimators=120

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image with MLflow
        run: |
          cd Workflow-CI/MLProject
          # Perintah ini membuat image Docker berisi model yang baru dilatih
          mlflow models build-docker -m "runs:/${{ github.run_id }}/model" -n "ad3whyu/car-price-predictor:latest"
          
      - name: Push Image to Docker Hub
        run: docker push ad3whyu/car-price-predictor:latest